import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import { Avatar, AvatarFallback } from "./_components/ui/avatar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <div className="flex items-center justify-end p-4 border-b">
            <Avatar>
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
